lgsm_dependencies:
  - curl
  - wget 
  - file 
  - tar 
  - bzip2 
  - gzip 
  - unzip 
  - bsdmainutils 
  - python 
  - util-linux 
  - ca-certificates 
  - binutils 
  - bc 
  - jq 
  - tmux 
  - netcat 
  - lib32gcc1 
  - lib32stdc++6 
  # - steamcmd

lgsm_version: 20.5.1
lgsm_user: "csgoserver"
lgsm_group: "csgoserver"

csgo_gslt_token: "steam_token"
csgo_defaultmap: de_dust2
csgo_maxplayers: 14
csgo_tickrate: 128
csgo_rcon_password: "supersecret"