ansible_python_interpreter: '/usr/bin/python3'

lgsm_dependencies:
  - bc
  - binutils
  - bsdmainutils
  - bzip2
  - ca-certificates
  - curl
  - file
  - gzip
  - jq
  - lib32gcc1
  - lib32stdc++6
  - net-tools
  - netcat
  - python
  - steamcmd
  - tar
  - tmux
  - unzip
  - util-linux
  - wget
