lgsm_dependencies:
  - curl
  - wget 
  - file 
  - tar 
  - bzip2 
  - gzip 
  - unzip 
  - bsdmainutils 
  - python 
  - util-linux 
  - ca-certificates 
  - binutils 
  - bc 
  - jq 
  - tmux 
  - netcat 
  - net-tools
  - lib32gcc1 
  - lib32stdc++6 
  - steamcmd

lgsm_user: csgoserver
lgsm_group: csgoserver

