plugin: amazon.aws.aws_ec2
regions:
  - eu-west-2
keyed_groups:
  # add hosts to tag_Name_value groups for each aws_ec2 host's tags.Name variable
  - key: tags.Name
    prefix: tag_Name_
    separator: ""
compose:
  ansible_host: public_ip_address