---

- hosts: tag_Name_csgo_server
  become: yes
  vars_files:
    - ./vars/defaults.yaml
  tasks:
  - name: Install LGSM dependencies (add i386 arch)
    command: dpkg --add-architecture i386
    when: ansible_architecture != 'i386'
  - name: Install LGSM dependencies (update package list)
    apt:
      update_cache: yes
  - name: SteamCMD (licence agreement)
    shell: 
      cmd: echo steam steam/question select "I AGREE" | sudo debconf-set-selections
  - name: SteamCMD (licence note)
    shell: 
      cmd: echo steam steam/license note '' | sudo debconf-set-selections
  - name: Install LGSM dependencies
    apt:
      name: "{{ item }}"
    loop: "{{ lgsm_dependencies }}"
  - name: Ensure LGSM Server Group exists
    group:
      name: "{{ lgsm_group }}"
      system: yes
  - name: Ensure LGSM Server user exists
    user:
      name: "{{ lgsm_user }}"
      group: "{{ lgsm_group }}"
      shell: /bin/bash
      system: yes
  - name: Download LGSM server creator
    get_url:
      url: https://linuxgsm.sh
      dest: "/home/{{ lgsm_user }}/linuxgsm.sh"
      mode: 0755
      owner: "{{ lgsm_user }}"